// Package analyzer provides local, non-AI implementations of domain.Analyzer.
// These let the full analysis workflow run and be tested without calling an
// external AI provider.
package analyzer

import (
	"context"
	"fmt"
	"strings"
	"unicode"

	"french-learning-app/internal/domain"
)

// RuleBased is a deterministic domain.Analyzer. Given the same entry it always
// produces the same result, which keeps local development and tests stable.
//
// It classifies an entry with cheap heuristics over the original input, mapping
// onto the shared domain fr_l2_taxonomy_v1 taxonomy (never a provider-specific
// category system):
//   - contains '?'            -> "comprehension" (asking about an utterance)
//   - multiple words          -> "grammar"       (a structured phrase)
//   - single word             -> "vocabulary"    (a lexical item)
//   - no alphabetic content   -> "other"         (no linguistic focus)
//
// Confidence reflects how strongly the heuristic matched; uncertainty records
// that this is a placeholder analyzer, not a real language model.
type RuleBased struct{}

// NewRuleBased returns a ready-to-use rule-based analyzer.
func NewRuleBased() *RuleBased { return &RuleBased{} }

// compile-time check.
var _ domain.Analyzer = (*RuleBased)(nil)

// Name identifies this analyzer in stored records.
func (RuleBased) Name() string { return "rule-based" }

// Analyze classifies the entry deterministically. It never returns an error;
// the signature keeps the interface uniform with future fallible analyzers.
func (RuleBased) Analyze(_ context.Context, entry *domain.Entry) (domain.AnalysisResult, error) {
	input := strings.TrimSpace(entry.OriginalInput)
	words := strings.Fields(input)

	var category domain.Category
	var confidence float64
	switch {
	case !containsLetter(input):
		// No alphabetic content means no linguistic focus to classify.
		category, confidence = domain.CategoryOther, 0.3
	case strings.Contains(input, "?"):
		category, confidence = domain.CategoryComprehension, 0.8
	case len(words) > 1:
		category, confidence = domain.CategoryGrammar, 0.6
	default:
		category, confidence = domain.CategoryVocabulary, 0.5
	}

	explanation := fmt.Sprintf(
		"Rule-based classification: %q mapped to %q (%d word(s)).",
		input, category, len(words),
	)

	uncertainty := "Generated by a deterministic rule-based analyzer, not a language model; treat as a placeholder."
	if category == domain.CategoryOther {
		uncertainty = "Input contains no alphabetic characters; classification is low confidence. " + uncertainty
	}

	return domain.AnalysisResult{
		Category:    category,
		Explanation: explanation,
		Confidence:  confidence,
		Uncertainty: uncertainty,
	}, nil
}

func containsLetter(s string) bool {
	for _, r := range s {
		if unicode.IsLetter(r) {
			return true
		}
	}
	return false
}
