// Package analyzer provides local, non-AI implementations of domain.Analyzer.
// These let the full analysis workflow run and be tested without calling an
// external AI provider.
package analyzer

import (
	"context"
	"fmt"
	"strings"
	"unicode"

	"french-learning-app/internal/domain"
)

// RuleBased is a deterministic domain.Analyzer. Given the same entry it always
// produces the same result, which keeps local development and tests stable.
//
// It classifies an entry with cheap heuristics over the original input:
//   - contains '?'            -> "question"
//   - multiple words          -> "phrase"
//   - single word             -> "vocabulary"
//
// Confidence reflects how strongly the heuristic matched; uncertainty records
// that this is a placeholder analyzer, not a real language model.
type RuleBased struct{}

// NewRuleBased returns a ready-to-use rule-based analyzer.
func NewRuleBased() *RuleBased { return &RuleBased{} }

// compile-time check.
var _ domain.Analyzer = (*RuleBased)(nil)

// Name identifies this analyzer in stored records.
func (RuleBased) Name() string { return "rule-based" }

// Analyze classifies the entry deterministically. It never returns an error;
// the signature keeps the interface uniform with future fallible analyzers.
func (RuleBased) Analyze(_ context.Context, entry *domain.Entry) (domain.AnalysisResult, error) {
	input := strings.TrimSpace(entry.OriginalInput)
	words := strings.Fields(input)

	var category string
	var confidence float64
	switch {
	case strings.Contains(input, "?"):
		category, confidence = "question", 0.8
	case len(words) > 1:
		category, confidence = "phrase", 0.6
	default:
		category, confidence = "vocabulary", 0.5
	}

	explanation := fmt.Sprintf(
		"Rule-based classification: %q looks like a %s (%d word(s)).",
		input, category, len(words),
	)

	uncertainty := "Generated by a deterministic rule-based analyzer, not a language model; treat as a placeholder."
	if !containsLetter(input) {
		uncertainty = "Input contains no alphabetic characters; classification is low confidence. " + uncertainty
		confidence = 0.3
	}

	return domain.AnalysisResult{
		Category:    category,
		Explanation: explanation,
		Confidence:  confidence,
		Uncertainty: uncertainty,
	}, nil
}

func containsLetter(s string) bool {
	for _, r := range s {
		if unicode.IsLetter(r) {
			return true
		}
	}
	return false
}
